app = "$FLY_APP"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"

[build]
image = "liuxingjun/proxy"

[env]
CADDY_DEBUG = "$CADDY_DEBUG"
CADDY_DOMAIN = "$CADDY_DOMAIN"
LOG_LEVEL = "info"

[[services]]
internal_port = 80
processes = ["app"]
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"
