# fly.toml file

# app = "example"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"

[build]
  image = "liuxingjun/proxy"

[env]
  DEBUG = "debug"
  DOMAIN = "example.fly.dev"
  # PRIMARY_REGION = "lax"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    # force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
