name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
     - '.github/**'
     - 'Dockerfile'
     - 'Caddyfile'
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: liuxingjun/proxy:latest
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.0.500
      - name: create fly.toml
        env:
          FLY_APP: ${{ env.FLY_APP }}
          CADDY_DOMAIN: ${{ env.CADDY_DOMAIN }}
          # CADDY_DEBUG: ${{ env.CADDY_DEBUG }}
        run: echo $FLY_APP;echo "--"; echo ${{ env.FLY_APP }}; env;envsubst < fly.template.toml > fly.toml && cat fly.toml
        
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
